import logging
import os
import re
import shutil
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Optional, Tuple
from urllib.parse import urlparse

from ._tpcgen_cli import TpcgenCli

logger = logging.getLogger(__name__)


class _TPCDSRsDataGenerator:
    COMPATIBILITY_MODE = "c"
    GEN_TABLE_REGISTRY = [
        "call_center",
        "catalog_page",
        "catalog_returns",
        "catalog_sales",
        "customer",
        "customer_address",
        "customer_demographics",
        "date_dim",
        "household_demographics",
        "income_band",
        "inventory",
        "item",
        "promotion",
        "reason",
        "ship_mode",
        "store",
        "store_returns",
        "store_sales",
        "time_dim",
        "warehouse",
        "web_page",
        "web_returns",
        "web_sales",
        "web_site",
    ]
    TARGET_FILE_SIZE_MAP = [
        (10, 128),
        (1024, 256),
        (5120, 512),
        (10240, 1024),
    ]
    # Measured from C-compatible SF10 output generated by the pinned tpcgen-cli
    # build with ZSTD(1), then normalized linearly to SF1000.
    SF1000_SIZE_GB_DICT = {
        "call_center": 0.001234,
        "catalog_page": 0.044884,
        "catalog_returns": 7.974819,
        "catalog_sales": 76.283314,
        "customer": 1.855254,
        "customer_address": 0.313774,
        "customer_demographics": 0.213324,
        "date_dim": 0.148512,
        "household_demographics": 0.002018,
        "income_band": 0.000124,
        "inventory": 41.242681,
        "item": 0.613306,
        "promotion": 0.002330,
        "reason": 0.000195,
        "ship_mode": 0.000262,
        "store": 0.001646,
        "store_returns": 11.737585,
        "store_sales": 96.769805,
        "time_dim": 0.074168,
        "warehouse": 0.000493,
        "web_page": 0.000703,
        "web_returns": 4.113903,
        "web_sales": 35.685844,
        "web_site": 0.001238,
    }
    ZSTD1_COMPRESSION_FACTOR_DICT = {
        "call_center": 1.251,
        "catalog_page": 2.819,
        "catalog_returns": 3.565,
        "catalog_sales": 4.655,
        "customer": 2.241,
        "customer_address": 3.062,
        "customer_demographics": 7.547,
        "date_dim": 2.605,
        "household_demographics": 3.743,
        "income_band": 1.0,
        "inventory": 1.019,
        "item": 3.297,
        "promotion": 2.958,
        "reason": 3.632,
        "ship_mode": 1.407,
        "store": 1.755,
        "store_returns": 4.165,
        "store_sales": 5.447,
        "time_dim": 4.144,
        "warehouse": 1.047,
        "web_page": 2.125,
        "web_returns": 3.429,
        "web_sales": 4.854,
        "web_site": 1.509,
    }
    SNAPPY_COMPRESSION_FACTOR_DICT = {
        "call_center": 1.147,
        "catalog_page": 1.748,
        "catalog_returns": 2.261,
        "catalog_sales": 2.655,
        "customer": 1.570,
        "customer_address": 1.923,
        "customer_demographics": 2.121,
        "date_dim": 1.619,
        "household_demographics": 1.819,
        "income_band": 1.0,
        "inventory": 1.009,
        "item": 2.062,
        "promotion": 1.919,
        "reason": 2.084,
        "ship_mode": 1.286,
        "store": 1.393,
        "store_returns": 2.481,
        "store_sales": 3.005,
        "time_dim": 2.082,
        "warehouse": 1.123,
        "web_page": 1.559,
        "web_returns": 2.207,
        "web_sales": 2.720,
        "web_site": 1.257,
    }
    ROW_GROUP_ESTIMATION_HEADROOM = 1.05
    CLOUD_SCHEMES = {"s3", "gs", "gcs", "abfs", "abfss", "adl", "wasb", "wasbs"}
    COMPRESSION_PATTERN = re.compile(
        r"^(UNCOMPRESSED|SNAPPY|LZO|LZ4|LZ4_RAW|GZIP(?:\(\d+\))?|BROTLI(?:\(\d+\))?|ZSTD\(\d+\))$"
    )

    def __init__(
        self,
        scale_factor: float,
        target_folder_uri: str,
        target_row_group_size_mb: int = 128,
        compression: str = "ZSTD(1)",
        table_list: Optional[List[str]] = None,
        multithreading: bool = True,
        executable: Optional[str] = None,
        compression_factor: Optional[float] = None,
    ) -> None:
        uri_scheme = urlparse(target_folder_uri).scheme.lower()
        if uri_scheme in self.CLOUD_SCHEMES:
            raise ValueError(
                f"{uri_scheme} protocol is not supported for TPC-DS Rust data generation. "
                "Use a local filesystem path or a mounted storage path."
            )
        if not 0 <= scale_factor <= 100000:
            raise ValueError("scale_factor must be between 0 and 100000, inclusive.")
        if target_row_group_size_mb <= 0:
            raise ValueError("target_row_group_size_mb must be greater than zero.")

        compression = compression.upper()
        if not self.COMPRESSION_PATTERN.fullmatch(compression):
            raise ValueError(f"Unsupported compression codec: {compression}")

        if compression_factor is not None and compression_factor < 1:
            raise ValueError("compression_factor must be greater than or equal to one.")

        requested_tables = table_list if table_list is not None else self.GEN_TABLE_REGISTRY
        unknown_tables = sorted(set(requested_tables) - set(self.GEN_TABLE_REGISTRY))
        if unknown_tables:
            raise ValueError(f"Unsupported TPC-DS tables: {', '.join(unknown_tables)}")
        if not requested_tables:
            raise ValueError("table_list must contain at least one table.")

        self.scale_factor = scale_factor
        self.target_folder = Path(target_folder_uri).expanduser().resolve()
        self.target_row_group_size_mb = target_row_group_size_mb
        self.compression = compression
        self.table_list = list(dict.fromkeys(requested_tables))
        self.compression_factor = compression_factor
        self.compression_factors_by_table = {
            table_name: self._resolve_compression_factor(table_name, compression_factor)
            for table_name in self.table_list
        }
        self.num_threads = (os.cpu_count() or 1) if multithreading else 1
        self.cli = TpcgenCli(executable)
        self.parts_by_table = {table_name: self._calculate_optimal_parts(table_name) for table_name in self.table_list}

    def run(self) -> None:
        self._prepare_target()
        for (part_count, compression_factor), table_names in self._group_tables_by_generation_settings().items():
            logger.info(
                "Generating TPC-DS tables %s with %d part(s), %.2f MB on-disk row groups, "
                "and a %.3f compression factor.",
                ", ".join(table_names),
                part_count,
                self.target_row_group_size_mb,
                compression_factor,
            )
            result = self.cli.run(self._build_command(self.target_folder, table_names, part_count, compression_factor))
            if result.stdout:
                logger.info(result.stdout.rstrip())
            if result.stderr:
                logger.info(result.stderr.rstrip())

        self._normalize_single_file_outputs()
        missing_outputs = [str(path) for path in self._expected_outputs() if not path.is_file()]
        if missing_outputs:
            raise RuntimeError("tpcgen-cli did not create expected files: " + ", ".join(missing_outputs))

    def _prepare_target(self) -> None:
        self.target_folder.mkdir(parents=True, exist_ok=True)
        for table_name in self.table_list:
            root_file = self.target_folder / f"{table_name}.parquet"
            if root_file.exists():
                root_file.unlink()
            table_folder = self.target_folder / table_name
            if table_folder.exists():
                shutil.rmtree(table_folder)

    def _normalize_single_file_outputs(self) -> None:
        for table_name in self.table_list:
            if self.parts_by_table[table_name] != 1:
                continue
            source_file = self.target_folder / f"{table_name}.parquet"
            if not source_file.is_file():
                continue
            table_folder = self.target_folder / table_name
            table_folder.mkdir(parents=True, exist_ok=True)
            shutil.move(str(source_file), str(table_folder / f"{table_name}.1.parquet"))

    def _expected_outputs(self) -> List[Path]:
        outputs = []
        for table_name in self.table_list:
            part_count = self.parts_by_table[table_name]
            table_folder = self.target_folder / table_name
            if part_count > 1:
                outputs.extend(
                    table_folder / f"{table_name}.{part_number}.parquet" for part_number in range(1, part_count + 1)
                )
            else:
                outputs.append(table_folder / f"{table_name}.1.parquet")
        return outputs

    def _group_tables_by_generation_settings(self) -> Dict[Tuple[int, float], List[str]]:
        grouped_tables = defaultdict(list)
        for table_name in self.table_list:
            settings = (
                self.parts_by_table[table_name],
                self.compression_factors_by_table[table_name],
            )
            grouped_tables[settings].append(table_name)
        return dict(grouped_tables)

    def _build_command(
        self,
        output_folder: Path,
        table_names: List[str],
        part_count: int,
        compression_factor: Optional[float] = None,
    ) -> List[str]:
        if compression_factor is None:
            factors = {self.compression_factors_by_table[table_name] for table_name in table_names}
            if len(factors) != 1:
                raise ValueError("Tables with different compression factors must be generated separately.")
            compression_factor = factors.pop()

        command = [
            "tpcds",
            "parquet",
            "--scale-factor",
            str(self.scale_factor),
            "--output-dir",
            str(output_folder),
            "--tables",
            ",".join(table_names),
            "--compat",
            self.COMPATIBILITY_MODE,
            "--compression",
            self.compression,
            "--row-group-bytes",
            str(
                round(
                    self.target_row_group_size_mb
                    * compression_factor
                    * self.ROW_GROUP_ESTIMATION_HEADROOM
                    * 1024
                    * 1024
                )
            ),
            "--num-threads",
            str(self.num_threads),
            "--parts",
            str(part_count),
            "--no-progress",
        ]
        return command

    def _calculate_optimal_parts(self, table_name: str) -> int:
        scaled_size_gb = self._estimated_table_size_gib(table_name)
        target_file_size_mb = self._target_file_size_mb(scaled_size_gb)
        return max(round(scaled_size_gb * 1024 / target_file_size_mb), 1)

    def _estimated_table_size_gib(self, table_name: str) -> float:
        zstd_size_gib = self.SF1000_SIZE_GB_DICT[table_name] * (self.scale_factor / 1000)

        return (
            zstd_size_gib
            * self.ZSTD1_COMPRESSION_FACTOR_DICT[table_name]
            / self.compression_factors_by_table[table_name]
        )

    def _target_file_size_mb(self, scaled_size_gb: float) -> int:
        for threshold_gb, target_size_mb in self.TARGET_FILE_SIZE_MAP:
            if scaled_size_gb < threshold_gb:
                return target_size_mb
        return 1024

    def _resolve_compression_factor(self, table_name: str, compression_factor: Optional[float]) -> float:
        if compression_factor is not None:
            return compression_factor
        if self.compression == "UNCOMPRESSED":
            return 1.0
        if self.compression == "ZSTD(1)":
            return self.ZSTD1_COMPRESSION_FACTOR_DICT[table_name]
        if self.compression == "SNAPPY":
            return self.SNAPPY_COMPRESSION_FACTOR_DICT[table_name]
        raise ValueError(
            f"compression_factor is required for {self.compression}; "
            "built-in measured defaults are available only for ZSTD(1) and SNAPPY."
        )
