from ._tpcgen_rs import _TpcgenRsDataGenerator


class _TPCHRsDataGenerator(_TpcgenRsDataGenerator):
    BENCHMARK_NAME = "tpch"
    BENCHMARK_LABEL = "TPC-H"
    GEN_TABLE_REGISTRY = [
        "customer",
        "lineitem",
        "nation",
        "orders",
        "part",
        "partsupp",
        "region",
        "supplier",
    ]
    # Measured from SF10 output generated by the pinned tpcgen-cli build with
    # ZSTD(1), then normalized linearly to SF1000.
    SF1000_SIZE_GB_DICT = {
        "customer": 7.755863,
        "lineitem": 145.739593,
        "nation": 0.000250,
        "orders": 36.859225,
        "part": 4.295145,
        "partsupp": 27.735921,
        "region": 0.000141,
        "supplier": 0.550992,
    }
    ZSTD1_COMPRESSION_FACTOR_DICT = {
        "customer": 2.956,
        "lineitem": 2.465,
        "nation": 2.027,
        "orders": 3.054,
        "part": 2.947,
        "partsupp": 3.800,
        "region": 1.268,
        "supplier": 2.702,
    }
    SNAPPY_COMPRESSION_FACTOR_DICT = {
        "customer": 1.974,
        "lineitem": 1.866,
        "nation": 1.570,
        "orders": 2.098,
        "part": 2.154,
        "partsupp": 2.789,
        "region": 1.149,
        "supplier": 1.858,
    }
