from ._tpcgen_rs import _TpcgenRsDataGenerator


class _TPCDSRsDataGenerator(_TpcgenRsDataGenerator):
    BENCHMARK_NAME = "tpcds"
    BENCHMARK_LABEL = "TPC-DS"
    COMMAND_ARGUMENTS = ("--compat", "c")
    GEN_TABLE_REGISTRY = [
        "call_center",
        "catalog_page",
        "catalog_returns",
        "catalog_sales",
        "customer",
        "customer_address",
        "customer_demographics",
        "date_dim",
        "household_demographics",
        "income_band",
        "inventory",
        "item",
        "promotion",
        "reason",
        "ship_mode",
        "store",
        "store_returns",
        "store_sales",
        "time_dim",
        "warehouse",
        "web_page",
        "web_returns",
        "web_sales",
        "web_site",
    ]
    SIZE_REFERENCE_SCALE_FACTOR = 10
    DEFINED_SCALE_FACTORS = (0, 1, 10, 100, 300, 1000, 3000, 10000, 30000, 100000)
    # Final output row counts from the TPC-DS scaling model. Fact and return
    # tables scale linearly and therefore do not need entries here.
    ROW_COUNT_SCALING = {
        "call_center": ("logarithmic", (0, 6, 24, 30, 36, 42, 48, 54, 60, 60)),
        "catalog_page": ("static", (0, 11718, 12000, 20400, 26000, 30000, 36000, 40000, 46000, 50000)),
        "customer": (
            "logarithmic",
            (0, 100000, 500000, 2000000, 5000000, 12000000, 30000000, 65000000, 80000000, 100000000),
        ),
        "customer_address": (
            "logarithmic",
            (0, 50000, 250000, 1000000, 2500000, 6000000, 15000000, 32500000, 40000000, 50000000),
        ),
        "customer_demographics": (
            "static",
            (0, 1920800, 1920800, 1920800, 1920800, 1920800, 1920800, 1920800, 1920800, 1920800),
        ),
        "date_dim": ("static", (0, 73049, 73049, 73049, 73049, 73049, 73049, 73049, 73049, 73049)),
        "household_demographics": ("static", (0, 7200, 7200, 7200, 7200, 7200, 7200, 7200, 7200, 7200)),
        "income_band": ("static", (0, 20, 20, 20, 20, 20, 20, 20, 20, 20)),
        "item": (
            "logarithmic",
            (0, 18000, 102000, 204000, 264000, 300000, 360000, 402000, 462000, 502000),
        ),
        "promotion": ("logarithmic", (0, 300, 500, 1000, 1300, 1500, 1800, 2000, 2300, 2500)),
        "reason": ("static", (0, 75, 75, 75, 75, 75, 75, 75, 75, 75)),
        "ship_mode": ("static", (0, 20, 20, 20, 20, 20, 20, 20, 20, 20)),
        "store": ("logarithmic", (0, 12, 102, 402, 804, 1002, 1350, 1500, 1704, 1902)),
        "time_dim": ("static", (0, 86400, 86400, 86400, 86400, 86400, 86400, 86400, 86400, 86400)),
        "warehouse": ("logarithmic", (0, 5, 10, 15, 17, 20, 22, 25, 27, 30)),
        "web_page": ("logarithmic", (0, 60, 200, 2040, 2604, 3000, 3600, 4002, 4602, 5004)),
        "web_site": ("logarithmic", (0, 30, 42, 24, 42, 54, 66, 78, 84, 96)),
    }
    # Measured from C-compatible SF10 output generated by the pinned tpcgen-cli
    # build with ZSTD(1), then normalized linearly to SF1000 for storage.
    SF1000_SIZE_GB_DICT = {
        "call_center": 0.001222,
        "catalog_page": 0.046315,
        "catalog_returns": 7.501222,
        "catalog_sales": 77.612198,
        "customer": 1.954509,
        "customer_address": 0.372212,
        "customer_demographics": 0.533869,
        "date_dim": 0.160342,
        "household_demographics": 0.002795,
        "income_band": 0.000129,
        "inventory": 40.881562,
        "item": 0.630520,
        "promotion": 0.002376,
        "reason": 0.000191,
        "ship_mode": 0.000256,
        "store": 0.001636,
        "store_returns": 11.303521,
        "store_sales": 94.989904,
        "time_dim": 0.086069,
        "warehouse": 0.000494,
        "web_page": 0.000703,
        "web_returns": 3.976669,
        "web_sales": 35.409775,
        "web_site": 0.001225,
    }
    ZSTD1_COMPRESSION_FACTOR_DICT = {
        "call_center": 1.166,
        "catalog_page": 2.632,
        "catalog_returns": 1.271,
        "catalog_sales": 1.279,
        "customer": 1.871,
        "customer_address": 2.394,
        "customer_demographics": 1.701,
        "date_dim": 2.243,
        "household_demographics": 1.629,
        "income_band": 1.0,
        "inventory": 1.026,
        "item": 2.717,
        "promotion": 2.144,
        "reason": 3.299,
        "ship_mode": 1.361,
        "store": 1.562,
        "store_returns": 1.267,
        "store_sales": 1.344,
        "time_dim": 3.194,
        "warehouse": 1.017,
        "web_page": 1.701,
        "web_returns": 1.223,
        "web_sales": 1.233,
        "web_site": 1.374,
    }
    SNAPPY_COMPRESSION_FACTOR_DICT = {
        "call_center": 1.073,
        "catalog_page": 1.685,
        "catalog_returns": 1.092,
        "catalog_sales": 1.067,
        "customer": 1.404,
        "customer_address": 1.703,
        "customer_demographics": 1.163,
        "date_dim": 1.511,
        "household_demographics": 1.122,
        "income_band": 1.0,
        "inventory": 1.007,
        "item": 1.808,
        "promotion": 1.470,
        "reason": 1.930,
        "ship_mode": 1.231,
        "store": 1.262,
        "store_returns": 1.109,
        "store_sales": 1.120,
        "time_dim": 1.863,
        "warehouse": 1.107,
        "web_page": 1.306,
        "web_returns": 1.072,
        "web_sales": 1.031,
        "web_site": 1.152,
    }

    def _estimated_table_size_gib(self, table_name: str) -> float:
        reference_size_gib = self.SF1000_SIZE_GB_DICT[table_name] * (self.SIZE_REFERENCE_SCALE_FACTOR / 1000)
        if table_name in self.ROW_COUNT_SCALING or table_name == "inventory":
            scale_ratio = self._expected_row_count(table_name, self.scale_factor) / self._expected_row_count(
                table_name, self.SIZE_REFERENCE_SCALE_FACTOR
            )
        else:
            scale_ratio = self.scale_factor / self.SIZE_REFERENCE_SCALE_FACTOR
        zstd_size_gib = reference_size_gib * scale_ratio
        return (
            zstd_size_gib
            * self.ZSTD1_COMPRESSION_FACTOR_DICT[table_name]
            / self.compression_factors_by_table[table_name]
        )

    @classmethod
    def _expected_row_count(cls, table_name: str, scale_factor: float) -> int:
        if table_name == "inventory":
            item_rows = cls._expected_row_count("item", scale_factor)
            item_ids = (item_rows // 6) * 3
            item_ids += (0, 1, 2, 2, 3, 3)[item_rows % 6]
            return item_ids * cls._expected_row_count("warehouse", scale_factor) * 261

        model, row_counts = cls.ROW_COUNT_SCALING[table_name]
        if scale_factor in cls.DEFINED_SCALE_FACTORS:
            return row_counts[cls.DEFINED_SCALE_FACTORS.index(scale_factor)]
        if model == "static":
            return row_counts[1]

        scale_slot = next(
            index for index, defined_scale in enumerate(cls.DEFINED_SCALE_FACTORS) if scale_factor <= defined_scale
        )
        lower_scale = cls.DEFINED_SCALE_FACTORS[scale_slot - 1]
        upper_scale = cls.DEFINED_SCALE_FACTORS[scale_slot]
        fraction = (scale_factor - lower_scale) / (upper_scale - lower_scale)
        base_row_count = row_counts[0] if scale_factor < 1 else row_counts[1]
        count = int(fraction * (row_counts[scale_slot] - row_counts[scale_slot - 1])) + base_row_count
        return count or 1
