from ._tpch_rs import _TPCHRsDataGenerator


class TPCHDataGenerator(_TPCHRsDataGenerator):
    """
    Generate TPC-H Parquet data with the bundled unified ``tpcgen-cli``.

    Parameters
    ----------
    scale_factor : float
        Scale factor that determines the generated dataset size.
    target_folder_uri : str
        Local or mounted folder where table directories are written.
    target_row_group_size_mb : int, default=128
        Target on-disk Parquet row-group size in megabytes.
    compression : str, default="ZSTD(1)"
        Parquet compression codec.
    table_list : list of str, optional
        TPC-H tables to generate. All eight tables are generated by default.
    multithreading : bool, default=True
        Use all available CPU cores when true, otherwise use one thread.
    compression_factor : float, optional
        Ratio of uncompressed to on-disk Parquet bytes. Measured per-table
        ZSTD levels use per-table factors measured with ``ZSTD(1)`` and
        ``SNAPPY`` uses its own measured factors; other compressed codecs
        require an explicit value.
    """
